### ISSUE TITLE
CJS issues?

### ISSUE THREAD

**Issue by sarink** [adcentury/material-spinner#1]
```
var $ = require('jquery');
require('material-spinner');
```

yields:

```
Uncaught ReferenceError: $ is not defined                 material.spinner.min.js
```

```
./~/material-spinner/dist/js/material.spinner.min.js
Critical dependencies:
1:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/material-spinner/dist/js/material.spinner.min.js 1:113-120
```

**Comment by adcentury** [comment]
Hi, @sarink 

this plugin doesn't contain jquery itself, so you need to install it yourself.

```
npm install jquery --save
```

will fix this issue.

**Comment by sarink** [comment]
@adcentury of course I've installed jquery, otherwise I wouldn't be able to require it. The problem (as it appears to me) is that the spinner module is looking for window.$ or window.jQuery, but jquery will only be scoped inside of my module that I'm requiring it from, and not global (so the spinner cannot see it).

Also, for this to be a CommonJS module, your "main" should point to the source file (see the second error above), and when you require it it should return some object (which serves as the public interface - perhaps it has a "spin" function and you pass it the element?).

**Comment by adcentury** [comment]
@sarink thanks for reporting, i have added a wrapper to make this module universal. see #2
