### ISSUE TITLE
IE 11 - Stroke is not linear

### ISSUE THREAD

**Issue by Purush0th** [adcentury/material-spinner#7]
See the image (or) load http://adcentury.github.io/material-spinner/ in IE 11

![image](https://cloud.githubusercontent.com/assets/1386902/12388154/27b437f0-bdf7-11e5-91e0-d08b295fb1e2.png)

**Comment by adcentury** [comment]
Thanks, @Purush0th . I've found it's because that svg animation not work in any version of IE. lol...

So, till now this lib is not support for IE.

However, I also found a solution here -> http://codepen.io/thebabydino/pen/CxkHm. Using js to play animation instead of css may work.
